sonar.projectKey=NestNet
sonar.projectName=NestNet
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
